FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Optional: install globally
RUN npm install -g ts-node nodemon

COPY . .


# Fix for Alpine + file watching
RUN apk add --no-cache dumb-init

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate dev && nodemon --watch src --exec ts-node src/index.ts"]
